apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-ds 
  region: us-east-1
vpc:
  id: vpc-07b949ca391ccfdfd # Use your existing VPC ID
  subnets:
    private:
      us-east-1a: { cidr: "10.0.200.0/24" }
      us-east-1b: { cidr: "10.0.2.0/24" }
    public:
      us-east-1a: { cidr: "10.0.1.0/24" }
      us-east-1b: { cidr: "10.0.100.0/24" }
nodeGroups:
  - name: ng-private
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: my-key-pair  # Make sure you create an SSH key pair before using this

