apiVersion: v1
kind: Service
metadata:
  name: wizapp-service
spec:
  type: LoadBalancer
  selector:
    app: wizapp  # Matches the label in wizapp-deployment.yaml
  ports:
  - protocol: TCP
    port: 80          # Exposes port 80 to the public
    targetPort: 8080  # Maps to container port 8080

